### PR TITLE
fix x64 Metadata loading

### PR DESCRIPTION
**Pull request by eloraiby**
this will fix the metadata entries, F# was used to read the C structures and action table then correlate between both and automatically correct the action file.
Note that the .h files in /scripts/ were modified manually to allow easy parsing

The code might require cleanup (some left-over debugging code ?)

### CODE REVIEW

**Comment by ncave** [comment]
@eloraiby Thanks, this is great.
Sorry, I introduced some conflicts so I had to merge it directly from your branch. Please get latest, I'll close this PR.

**Comment by eloraiby** [comment]
As long as proper credit is given, no problem :)

**Comment by ncave** [comment]
@eloraiby Absolutely, let me know if you want me to go back and redo it, I can rearrange the order of commits so that all your commits are listed, no problem.

**Comment by ncave** [comment]
@eloraiby I redid the order of importing so that your individual commits are showing (not squashed). Sorry about that, I should have done this to start with, please get latest.

**Comment by ncave** [comment]
@eloraiby Also, I'll rename the `scripts` folder to `tools`, if you don't mind, just so people don't get confused.

**Comment by eloraiby** [comment]
@ncave sorry for the delay, reordering the commits wasn't necessary, sorry for all the hassle. renaming scripts to tools is a good idea. I gave up and started running a static analyser and it's finding a lot of potential issues that require fixing to address the x64 issue, probably fixing other bugs as well.

**Comment by ncave** [comment]
@eloraiby Awesome, less bugs is always good. I'm currently struggling with #27, it takes a lot of time.

**Comment by ncave** [comment]
@eloraiby Ok, #27 is fixed, it was a well hidden JIT eval stack issue that was causing all the trouble.

**Pull request closed without merging**
